server:
  port: 2000

spring:
  application:
    name: config-master
  cloud:
    config:
      profile: dev
      server:
        git:
          uri: https://github.com/hack-feng/maple-cloud-properties
          search-paths: /
          username: 
          password: 
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
