server:
  port: 2000

spring:
  application:
    name: config-master
  rabbitmq:
    host: 47.101.181.228
    port: 5672
    username: admin
    password: zhangQQ123456
  cloud:
    config:
      profile: dev
      server:
        git:
          uri: https://github.com/hack-feng/maple-cloud-properties
          search-paths: /
          username: 
          password: 
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
